title: Yoga Pramudita # your name (or website title) here
logo: "/images/Group.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify"> Yoga Pramudita (or oftenly called Yoga), 20 years old, is a student at Universitas Muhamadiyah Surakarta (UMS) majoring in Informatics Technology. 
  In college not only focusing on my study for academic purpose, but also actively participated in non-academic like organization.</p>
  <p align="justify"> Now I am a comitee in Organization Division at FOSTI UMS. In organization it’s taught me on having soft skills such as teamwork, communication, and dedication.
  I also have strong will to learn and develop myself to become the best versions of myself.</p>
  <br>
  <a href="https://www.linkedin.com/in/yoga-pramudita-738411212/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
